name: Run Maven Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@master
    - name: Setup Chrome Browser
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Run tests
      run: mvn -B test -Dgroups=release
    - name: Generate Surefire Report
      run: mvn surefire-report:report
    - name: Upload Surefire Report
      uses: actions/upload-artifact@v2
      with:
        name: Test Report
        path: ${{ github.workspace }}/target/site/surefire-report.html
